### ISSUE TITLE
Integration Teil 2 in Block5 - map.htm

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#10]

**Comment by e1025108** [comment]
Sucheingabe und MapCenter auf Basis der BoundingBox integriert @Elimnio

**Comment by e1025108** [comment]
Accuracy Circle = ol.geolocation.getAccuracy Anpassung der BoundingBox

**Comment by e1025108** [comment]
@ahocevar 
Wir haben das Problem, dass die geolocation nur das Attribut "accuracy" (Angabe in m) enthält und es mir einfach nicht gelingt, mit dem Koordinatenpunkt einen Kreis + Radius zu zeichnen und aus dem einen Extent zu ziehen, der dann wieder für den View verwendet wird. Ist das überhaupt das richtige Vorgehen?

**Comment by e1025108** [comment]
Solved.

**Comment by Elimnio** [comment]
Cool danke! :) probiers aber gerne dann zuhaus noch aus :)
Am 03.12.2014 20:31 schrieb "Ben L." notifications@github.com:

**Comment by ahocevar** [comment]
Oh sorry, eure Notification ist irgendwie in der Flut untergegangen. Hauptsache es ist gelöst! :smile:

**Comment by e1025108** [comment]
@ahocevar 
Jetzt ist es gelöst. Aber dazu mussten wir erst drauf kommen, dass die richtigen Infos in der Online-Doku von OL3 zu sehen sind, wenn man den Haken bei "stable" entfernt :santa:
