### ISSUE TITLE
Benachrichtigung Auftraggeber

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#18]
Die grobe Projektplanung ist abgeschlossen und die Meilenstein-Übersicht kann hier eingesehen werden: https://github.com/tuwien-geoweb/g05-2014/milestones Die Meilensteine enthalten den aktuellen Arbeitsstand als Issues.
@ahocevar 
@jbroetha

**Comment by ahocevar** [comment]
Sehr schön ausgearbeitet. Aus meiner Sicht könnt ihr loslegen und nach diesem Plan vorgehen.
