### ISSUE TITLE
Fehler bei Kommentar-Funktion (Error Inserting Features)

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#25]
@ahocevar 
Wir stehen noch etwas an beim Kartenprojekt aus Block 6. Es ist uns gelungen, die Fehlermeldung des GeoServers als Antwort auf das Setzen des Kommentars auf der Karte herauszuführen:
![image](https://cloud.githubusercontent.com/assets/9716568/5394494/5e75e6cc-813e-11e4-9cb3-d5a0101af8c0.png)
Den Fehler hatten andere Kollegen im Block 4 (glaube ich). Woran kann das liegen? Ich habe am Geoserver die Konfiguration von uns (G05) mit Gruppe G07 verglichen - identisch. Haben Sie da noch eine Idee?

**Comment by ahocevar** [comment]
Das Problem ist der räumliche Index. Aus irgend einem Grund erstellt Spatialite-GUI in der Version, die wir heuer verwenden, einen ungültigen räumlichen Index. Am besten ihr löscht die comments-Tabelle noch einmal komplett, und erstellt sie neu, aber ohne räumlichen Index. Ich habe die Folie diesbezüglich auch aktualisiert: http://ahocevar.net/tuwien-geoweb/block6.html#/11

Wenn ihr das erledigt habt, in GeoServer noch einmal die Datenspeicher-Konfiguration aufrufen und neu speichern. Danach in die Layer-Konfiguration, und ganz unten "Feature type neu laden" anklicken und speichern.

**Comment by e1025108** [comment]
Beim ersten Versuch hat es nicht geklappt - morgen folgt der Zweite...

**Comment by e1025108** [comment]
@ahocevar 
Würde es auch zum Ziel führen, wenn ich die comments-Tabelle aus einer SpatiaLite-DB exportiere, wo es funktioniert?

**Comment by ahocevar** [comment]
Das würde auch funktionieren. Aber die zwei Schritte danach im GeoServer müsst ihr trotzdem machen.

**Comment by e1025108** [comment]
Kann derzeit den GeoServer nicht erreichen, bekomme einen 502 Proxy Error.

**Comment by jbroetha** [comment]
Ich werde den EDV-Techniker informieren – ggf. Neustart …

MfG
J. Bröthaler

Von: Ben L. [mailto:notifications@github.com]
Gesendet: Freitag, 12. Dezember 2014 18:06
An: tuwien-geoweb/g05-2014
Betreff: Re: [g05-2014] Fehler bei Kommentar-Funktion (Error Inserting Features) (#25)

Kann derzeit den GeoServer nicht erreichen, bekomme einen 502 Proxy Error.

**Comment by e1025108** [comment]
Okay, vielen Dank!

**Comment by jbroetha** [comment]
Server wurde neu gestartet - hoffe, es passt alles ...
MfG
J. Bröthaler

Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: "Ben L." notifications@github.com
Datum:12.12.2014 18:30 (GMT+01:00)
An: tuwien-geoweb/g05-2014 g05-2014@noreply.github.com
Cc: Bröthaler Johann johann.broethaler@tuwien.ac.at
Betreff: Re: [g05-2014] Fehler bei Kommentar-Funktion (Error Inserting Features) (#25)

Okay, vielen Dank!

**Comment by e1025108** [comment]
Das ging wirklich flott! :+1:

**Comment by e1025108** [comment]
Issue solved - danke an @ahocevar und @jbroetha !
Block6 ist somit funktionsfähig abgeschlossen.
