### ISSUE TITLE
Frage zur Skalierung von Icons eines Punktlayers

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#28]
@ahocevar 
Ich komme nicht so recht weiter. Das ist zwar nur Kosmetik, es wurmt mich aber schon ein wenig. Ich habe die CarSharing-Standorte wie folgt eingebunden:
var CarSharing = new ol.layer.Vector({
  source: new ol.source.GeoJSON({
    url: 'http://student.ifip.tuwien.ac.at/geoserver/g05_2014/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=g05_2014:CARSHARINGOGDPoint&outputFormat=json',
    projection: 'EPSG:3857'
  }),
    style: new ol.style.Style({
       image: new ol.style.Icon({src: 'http://data.wien.gv.at/katalog/images/carsharingogd.png', })
    })
});

Kann ich die Größe der Icons in der OL-Map noch programmatisch skalieren? Ich habe es mit "size: [16, 16]" hinter dem Tag src probiert, aber ohne Erfolg.

Danke schonmal!

**Comment by ahocevar** [comment]
Die option ist `scale`, nicht `size`:

``` js
new ol.style.Icon({src: 'http://data.wien.gv.at/katalog/images/carsharingogd.png', scale: 0.5});
```

**Comment by e1025108** [comment]
Besten Dank!
