### ISSUE TITLE
Bitte um Neustart des GeoServers

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#30]
@ahocevar @jbroetha 

Danke!

**Comment by e1025108** [comment]
U.N.F.A.S.S.B.A.R schnell! Merci!

**Comment by jbroetha** [comment]
…wurde neu gestartet …

MfG
J. Bröthaler

Von: Ben L. [mailto:notifications@github.com]
Gesendet: Dienstag, 13. Jänner 2015 16:04
An: tuwien-geoweb/g05-2014
Cc: Bröthaler Johann
Betreff: [g05-2014] Bitte um Neustart des GeoServers (#30)

@ahocevarhttps://github.com/ahocevar @jbroethahttps://github.com/jbroetha

Danke!

**Comment by jbroetha** [comment]
… und zur Stabilität des Geoservers werde ich am Donnerstag dann wohl eine zerknirschte Rede halten müssen …

Ansonsten: Bravo - weiter so engagiert …

LG
JB

Von: Ben L. [mailto:notifications@github.com]
Gesendet: Dienstag, 13. Jänner 2015 16:15
An: tuwien-geoweb/g05-2014
Cc: Bröthaler Johann
Betreff: Re: [g05-2014] Bitte um Neustart des GeoServers (#30)

U.N.F.A.S.S.B.A.R schnell! Merci!

**Comment by iemg** [comment]
ad Rede: :+1: :smiley:

**Comment by e1025108** [comment]
[loriot]Eine Rede, eine Rede![/loriot] :grinning:

**Comment by e1025108** [comment]
@ahocevar @jbroetha 

Ich glaub, diesmal hab ich den GeoServer auf dem Gewissen... Bitte um Neustart, reicht aber auch erst morgen früh.
