### ISSUE TITLE
Abschließender Test und Abgabe

### ISSUE THREAD

**Issue by e1025108** [tuwien-geoweb/g05-2014#8]
- Kommentar an Übungsleiter

**Comment by e1025108** [comment]
+Release nicht vergessen! :smile:

**Comment by e1025108** [comment]
@ahocevar 
Release erstellt, Feedback-Formular mit zusätzlich zum JS integrierten Feedback-Handler funktioniert nur über den ifip-Server: http://student.ifip.tuwien.ac.at/geoweb/2014/g05/page/intranet/intranet.htm

**Comment by ahocevar** [comment]
Funktioniert leider nicht (Safari/OSX). Die Position wird nicht übermittelt. Offenbar wird nur der PHP-Handler aufgerufen.

**Comment by e1025108** [comment]
Wird nochmal überprüft. @ahocevar Welche OSX/Safari-Version wurde da genutzt?

**Comment by e1025108** [comment]
Kompatibilität mit Google Chrome, FF und IE11 erfolgreich getestet. Safari noch ausstehend, möglicherweise behandelt Safari das JS im Submit als Popup und blockiert bei aktivem Popup-Blocker die Verarbeitung. @ahocevar

**Comment by ahocevar** [comment]
OSX 10.10.1, Safari 8.0.

**Comment by ahocevar** [comment]
Popup-Blocker nicht aktiviert.

**Comment by ahocevar** [comment]
Hab noch einmal getestet - jetzt funktioniert's!
